# Generated by Django 5.1.6 on 2025-02-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_inventory_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='product',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('ethanol', 'Ethanol')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('ethanol', 'Ethanol')], max_length=255),
        ),
    ]
