# Generated by Django 5.1.6 on 2025-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usertwofactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertwofactor',
            name='verification_code',
            field=models.IntegerField(unique=True),
        ),
    ]
