# Generated by Django 5.1.6 on 2025-03-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usertwofactor_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
